version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "24"
  jobs:
    install:
      # Install dependencies
      - npm ci
    build:
      # Build the site
      - npm run docs
      # Copy generated files into Read the Docs directory
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --verbose --recursive docs/* $READTHEDOCS_OUTPUT/html/
